spring:
  datasource:
    url: jdbc:mysql://192.168.68.128:3306/tensquare_user?characterEncoding=UTF8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
mybatis:
  type-aliases-package: com.example.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000
